name: Update
on:
  workflow_dispatch:
permissions: write-all
jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Checkout this
        uses: actions/checkout@v6
      - name: Make temp
        run: "mkdir ./temp"
      - name: Checkout Cyrus
        uses: actions/checkout@v6
        with:
          repository: CyrusCraft/Cyrus
          ref: main
          token: ${{ secrets.CYRUS_READ_ONLY }}
          path: "./temp"
      - name: Build docs
        run: ./gradlew docs
        working-directory: "./temp"
      - name: Move API docs
        run: move ./temp/api/build/docs/ ./Docs/API
      - name: Cleanup
        run: rmdir /S /Q ./temp
      - name: Commit changes
        uses: actions-x/commit@v6
          
      

